spring:
  application:
    name: Main
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: flashypotato
    password: mistapotato
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
#logging:
#  level:
#    root: ERROR

server:
  servlet:
    session:
      timeout: 15m